name: "Asset test"

on:
  push:

permissions:
  contents: write
  actions: read
  checks: write
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  upload-assets:
    name: "Upload assets"
    runs-on: ubuntu-latest
    steps:
      - name: "Fake make some files"
        run: |
          echo "First" > test-1.txt
          echo "Second" > test-2.txt
          echo "Third" > test-3.txt
          ls -l
      - name: "Upload assets latest release"
        uses: alexellis/upload-assets@0.3.0 # also tried 0.2.2
        env:
          ACTIONS_STEP_DEBUG: true
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths:  '["test-*"]'
